/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Datos.ArchivoOrdenes;
import Datos.ArchivoPreOrdenes;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import proyecto.Controlador;
import proyecto.Correo;

/**
 *
 * @author Admie21
 */
public class listaPreordenesCanciones extends javax.swing.JFrame {
    
    ArchivoPreOrdenes archivoPreOrdenes = new ArchivoPreOrdenes();
    ArchivoOrdenes archivoOrdenes = new ArchivoOrdenes();
    
    private String correo = "";
    Correo a = new Correo();
    
    private DefaultListModel modelo;
    private int seleccion = -1;
   
  
    /**
     * Creates new form listaPreordenesCanciones
     */
    public listaPreordenesCanciones() {
        initComponents();
        
        setLocationRelativeTo(null);
        setResizable(false);

        setTitle("Tienda de discos");
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Disco.jpg")).getImage());

        ((JPanel) getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/Imagenes/Disco.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());
        
        modelo = new DefaultListModel();
        listaPreordenesCanciones.setModel(modelo);
        
        String datosCanciones[]=archivoPreOrdenes.listaPreOrdenesCanciones();
        
        /**
         * Aqui se convierte el arreglo para 
         * recorrerlo y añadir su contenido al Jlist de Pre Ordenes
         */
        for (int i = 0; i < datosCanciones.length; i++) {
            
             modelo.addElement(datosCanciones[i]);
 
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaPreordenesCanciones = new javax.swing.JList<>();
        btnRegresar = new javax.swing.JButton();
        btnAtender = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(listaPreordenesCanciones);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnAtender.setText("Atender");
        btnAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtender)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(btnAtender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)))
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        
        Mantenimiento ventana = new Mantenimiento();
        ventana.pack();
        ventana.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderActionPerformed
        // TODO add your handling code here:
        
        String datos[] =listaPreordenesCanciones.getSelectedValue().split(";");
        String preOrdenParaOrdenAlbum=listaPreordenesCanciones.getSelectedValue();
        
        int indicePreOrden=listaPreordenesCanciones.getSelectedIndex();
        String nombreAlbum=datos[0];
        correo=datos[5];
        
        String cantidadNueva= JOptionPane.showInputDialog("Introduzca la Nueva Cantidad del Articulo "+nombreAlbum+":");
        enviarCorreoElectronicoExitoPreOrdenAlbum(cantidadNueva, nombreAlbum);
        
        if(Integer.parseInt(cantidadNueva)>Integer.parseInt(datos[2])){
        
            archivoPreOrdenes.removerPreOrdenCanciones(nombreAlbum,datos[1]);
            archivoOrdenes.registrarOrden("cancionesOrdenes.txt", preOrdenParaOrdenAlbum);
            enviarCorreoElectronicoExitoPreOrdenAlbum(cantidadNueva, nombreAlbum);
            
        }
        
        archivoPreOrdenes.atenderPreOrdenCanciones(nombreAlbum,datos[1],cantidadNueva);
    }//GEN-LAST:event_btnAtenderActionPerformed

    /**
     * Metodo que envia un mail cuando se cumple con una pre orden
     * de un album de musica de la Tienda de Discos
     * @param cantidadArticulo String la cantidad del articulo
     * @param nombreAlbum String nombre del articulo
     */
    public void enviarCorreoElectronicoExitoPreOrdenAlbum(String cantidadArticulo,String nombreAlbum) {

        a.setContraseña("cnaipcaudzpcbdqh");
        a.setUsuario("anthonnyc10@gmail.com");
        a.setAsunto("Compra exitosa");
        a.setMensaje("Su Pre Orden se cumplio correctamente \nEl nombre del Album que compro es : " + nombreAlbum + "\nCantidad : "+cantidadArticulo);
        a.setDestino(correo);
        a.setNombreArchivo("Azul.jpg");
        a.setRutaArchivo("Azul.jpg");
        a.setAsunto(" Su Pre Orden se realizo con Exito , disfrute de su producto !!!");
        Controlador b = new Controlador();

        if (b.enviarCorreo(a)) {
            JOptionPane.showMessageDialog(null, "Envio correcto");
        } else {

            JOptionPane.showMessageDialog(null, "error");

        }

    }   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listaPreordenesCanciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listaPreordenesCanciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listaPreordenesCanciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listaPreordenesCanciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listaPreordenesCanciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaPreordenesCanciones;
    // End of variables declaration//GEN-END:variables
}
