/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 *
 * @author Anthonny
 */
public class PrincipalUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalUsuarios
     */
    public PrincipalUsuarios() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Tienda de discos");
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Disco.jpg")).getImage());
        ((JPanel) getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/Imagenes/Disco.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        buscarMusica = new javax.swing.JMenuItem();
        comprarMusica = new javax.swing.JMenuItem();
        buscarPelicula = new javax.swing.JMenuItem();
        comprarPelicula = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Opciones");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        buscarMusica.setText("Buscar Musica");
        buscarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMusicaActionPerformed(evt);
            }
        });
        jMenu1.add(buscarMusica);

        comprarMusica.setText("Comprar  Musica");
        comprarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarMusicaActionPerformed(evt);
            }
        });
        jMenu1.add(comprarMusica);

        buscarPelicula.setText("Buscar Pelicula");
        buscarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPeliculaActionPerformed(evt);
            }
        });
        jMenu1.add(buscarPelicula);

        comprarPelicula.setText("Comprar Pelicula");
        comprarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarPeliculaActionPerformed(evt);
            }
        });
        jMenu1.add(comprarPelicula);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMusicaActionPerformed
        // TODO add your handling code here:
        BuscarMusica ventana = new BuscarMusica();
        ventana.pack();
        ventana.setVisible(true);
        setVisible(false);
      

    }//GEN-LAST:event_buscarMusicaActionPerformed

    private void buscarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPeliculaActionPerformed
        // TODO add your handling code here:

        buscarPeliculas ventanaBuscarPelicula = new buscarPeliculas();
        ventanaBuscarPelicula.pack();
        ventanaBuscarPelicula.setVisible(true);
        setVisible(false);
        System.out.println("Buscando Peliculas");

    }//GEN-LAST:event_buscarPeliculaActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
  
    }//GEN-LAST:event_jMenu1MouseClicked

    private void comprarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarPeliculaActionPerformed
        // TODO add your handling code here:
      
        ComprarPelicula ventanaInicioUsuarioUsuario = new ComprarPelicula();
        ventanaInicioUsuarioUsuario.pack();
        ventanaInicioUsuarioUsuario.setVisible(true);
        setLocationRelativeTo(null);
        System.out.println("Compando Pelicula");
      
    }//GEN-LAST:event_comprarPeliculaActionPerformed

    private void comprarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarMusicaActionPerformed
        // TODO add your handling code here:
        
       ComprarMusica ventanaComprarMusica = new ComprarMusica();
       ventanaComprarMusica.pack();
       ventanaComprarMusica.setVisible(true);
        setLocationRelativeTo(null);
       
    }//GEN-LAST:event_comprarMusicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem buscarMusica;
    private javax.swing.JMenuItem buscarPelicula;
    private javax.swing.JMenuItem comprarMusica;
    private javax.swing.JMenuItem comprarPelicula;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
